name: "Auto Scraper"
description: "Auto Scraper"
author: "ajithmanmu@gmail.com"

# inputs:
#   MY_NAME:
#     description: "Who to greet"
#     required: true
#     default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
