export interface overviewValidator {
  [name: string] : any,
  price? : string,
  image? :string,
  Our_Rating? : string,
  Fuel_type_propulsion ? : string,
  Engine_displacement ? : string,
  Body_style ? : string,
  Doors ? : string,
  Seats ? : string,
  Crash_Test_Rating ? : string,
  Airbags ? : string,
  Max_Power ? : string,
  Max_Torque ? : string,
  Gearbox_Type ? : string,
  Claimed_Electric_Motor_Range ? : string,
  Warranty_Distance ? : string,
  Warranty_Duration ? : string,
}
export interface dimensionsValidator {
  [Length: string] : any,
  Width?: string,
  Height?: string,
  Wheelbase?: string,
  Ground_Clearance?: string,
  Kerb_Weight?: string,
  Boot_Capacity?: string,
}
export interface engineMotorValidator {
  [Combined_Max_Power: string] : any,
  Combined_Max_Torque?: string,
  Engine_Displacement?: string,
  Engine_Installation?: string,
  Engine_Type?: string,
  Fuel_Type_Propulsion?: string,
  Max_Engine_Power?: string,
  Max_Engine_Power_CNG?: string,
  Max_Engine_Power_LPG?: string,
  Max_Engine_Torque?: string,
  Max_Engine_Torque_CNG?: string,
  Max_Engine_Torque_LPG?: string,
  Max_Motor_Power?: string,
  Max_Motor_Torque?: string,
  Motor_Type?: string,
}
export interface transmissionValidator {
  [Drive_Layout: string] : any,
  Gearbox_Type?: string,
  Manual_Shifts_via_Gear_Lever_on_Automatic_Gearbox?: string,
  Number_Of_Gears?: string,
  Paddle_Shifters_for_Automatic_Gearbox?: string,
  Selectable_Differential_Lock?: string,
  Sport_Mode_for_Automatic_Gearbox?: boolean,
}
export interface fuelEconomyRangeValidator {
  Auto_Start_Stop?: boolean,
  [Battery_Capacity: string] : any,
  CNG_LPG_Tank_Capacity?: string,
  Charging_Time?: string,
  City_Fuel_Economy_as_Tested?: string,
  Claimed_Range?: string,
  Fuel_Tank_Capacity?: string,
  Highway_Fuel_Economy_as_Tested?: string,
  Official_Fuel_Economy?: string,
}
export interface suspensionValidator {
  Damper_Control?: boolean,
  [Front_Springs: string] : any,
  Front_Suspension_Type?: string,
  Rear_Springs?: string,
  Rear_Suspension_Type?: string,
  Ride_Height_Adjust?: string,
}
export interface steeringValidator {
  [Steering_Adjust: string] : any,
  Steering_Adjust_Type?: string,
  Turning_Radius?: string,
  Type_Of_Power_Assist?: string,
}
export interface wheelsValidator {
  [Front_Tyre_Size: string] : any,
  Rear_Tyre_Size?: string,
  Spare_Wheel?: string,
  Wheel_Size?: string,
  Wheels?: string,
}
export interface brakesValidator {
  [Front_Brakes: string] : any,
  Rear_Brakes?: string,
}
export interface safetyValidator {
  Adaptive_Cruise_Control?: string,
  [Airbags: string] : any,
  Anti_Lock_Brakes__ABS_?: boolean,
  Anti_Pinch_Power_Windows?: string,
  Automatic_Headlamps?: boolean,
  Automatic_Wipers?: boolean,
  Blind_Spot_Monitor?: string,
  Brake_Assist__BA_?: boolean,
  Central_Locking?: boolean,
  Child_Safety_Lock?: boolean,
  Day_Night_Interior_Mirror?: string,
  Electronic_Brakeforce_Distribution__EBD_?: boolean,
  Electronic_Parking_Brake?: boolean,
  Electronic_Stability_Control?: boolean,
  Global_NCAP_Crash_Test_Rating?: string,
  Hill_Descent_Control?: string,
  Hill_Start_Assist?: boolean,
  ISOFIX_Child_Seat_Mounts?: boolean,
  Parking_Camera?: string,
  Parking_Sensors?: string,
  Rear_Defogger?: boolean,
  Rear_Washer_Wiper?: string,
  Speed_Sensing_Auto_Door_Locks?: boolean,
  Traction_Control?: boolean,
  Tyre_Pressure_Monitoring_System?: boolean,
}
export interface exteriorValidator {
  Body_Coloured_Bumpers?: boolean,
  Daytime_Running_Lights?: string,
  [Front_Fog_Lamps: string] : any,
  Headlight_Type?: string,
  Projector_Headlamps?: boolean,
}
export interface upholsteryValidator {
  Adjustable_Front_Headrests?: boolean,
  Adjustable_Rear_Headrests?: boolean,
  Driver_s_Seat_Height_Adjust?: boolean,
  Driver_s_Seat_Memory?: boolean,
  Electric_Adjust_for_Driver_s_Seat?: boolean,
  Electric_Adjust_for_Front_Passenger_s_Seat?: boolean,
  Front_Passenger_Seat_Height_Adjust?: boolean,
  Front_Passenger_Seat_Memory?: boolean,
  Front_Seat_Armrest?: boolean,
  [Heated_Seats: string] : any,
  Individual_Chairs_at_Rear?: string,
  Leather_wrapped_Gear_Knob?: string,
  Leather_wrapped_Steering_Wheel?: boolean,
  Massage_Seats?: string,
  Rear_Seat_Armrest?: boolean,
  Rear_Seat_Backrest_Fold?: string,
  Rear_Seat_Backrest_Recline?: string,
  Rear_Seat_Backrest_Split?: string,
  Seats?: string,
  Third_Row_Seats?: string,
  Third_Row_Seats_Fold?: string,
  Third_Row_Seats_Split?: string,
  Ventilated_Seats?: string,
}
export interface infotainmentValidator {
  AUX_Input?: boolean,
  Android_Auto?: string,
  Apple_CarPlay?: string,
  Audio_System?: boolean,
  Bluetooth_Audio_Streaming?: boolean,
  Bluetooth_Telephone_Function?: boolean,
  CD_Player?: boolean,
  [Display: string] : any,
  Gesture_Controls?: string,
  MirrorLink?: string,
  Rear_Entertainment_Screens?: string,
  Satellite_Navigation?: string,
  Steering_Audio_Controls?: boolean,
  Steering_Phone_Controls?: boolean,
  Touchpad?: string,
  USB_Input?: boolean,
  Video_Player?: boolean,
  Voice_Commands?: boolean,
  Web_Browser?: string,
  Wireless_Phone_Charging?: string,
}
export interface comfortValidator {
  [Auto_Parking: string] : any,
  Climate_Control?: string,
  Configurable_Ambient_Lighting?: string,
  Cruise_Control?: boolean,
  Dead_Pedal?: boolean,
  Driving_Modes?: boolean,
  Exterior_Mirrors_Electric_Adjust?: boolean,
  Exterior_Mirrors_Electric_Fold?: boolean,
  Front_Passenger_Seat_Adjust_from_Rear?: string,
  Hands_free_Boot_Opening?: string,
  Keyless_Entry?: string,
  Launch_Control?: string,
  Power_Windows?: string,
  Power_Windows_with_One_Touch_Down?: string,
  Power_Windows_with_One_Touch_Up?: string,
  Push_Button_Start?: boolean,
  Rear_AC_Vents?: boolean,
  Rear_Power_Outlet?: boolean,
  Rear_Window_Sun_Shades?: string,
  Rear_Windscreen_Sun_Shade?: string,
  Remote_Locking?: boolean,
  Sunroof?: string,
  Third_Row_AC_Vents?: string,
}
export interface instrumentationValidator {
  Average_Fuel_Consumption?: boolean,
  Average_Speed?: boolean,
  Distance_to_Empty?: boolean,
  Gear_Indicator?: boolean,
  Head_up_Display?: string,
  Instantaneous_Consumption?: boolean,
  Low_Fuel_Level_Warning?: boolean,
  Shift_Indicator?: string,
  [Speedometer: string] : any,
  Tachometer?: string,
  Trip_Meter?: boolean,
}
export interface autoDataValidator {
  make: string,
  model: string,
  variant: string,
  type: string,
  price: string,
  image: string,
  name: string,
  overview: overviewValidator,
  specifications:{
    dimensions: dimensionsValidator,
    engineMotor: engineMotorValidator,
    transmission: transmissionValidator,
    fuelEconomyRange: fuelEconomyRangeValidator,
    suspension: suspensionValidator,
    steering: steeringValidator,
    wheels: wheelsValidator,
    brakes: brakesValidator,
  },
  features: {
    safety: safetyValidator,
    exterior: exteriorValidator,
    upholstery: upholsteryValidator,
    infotainment: infotainmentValidator,
    comfort: comfortValidator,
    instrumentation: instrumentationValidator,
  },
  metadata: {
    refUrl: string,
    createdAt: Date,
  }
}

export type urlType = {
  id: string;
  url: string;
}